export const {
    VITE_PAYPAL_ID: PAYPAL_ID,
    VITE_PAYPAL_SECRET: PAYPAL_SECRET,
    VITE_PAYPAL_URL: PAYPAL_URL,
    VITE_PRO_M_ID: PRO_M,
    VITE_PRO_Y_ID: PRO_Y,
    VITE_PREMIUM_M_ID: PREMIUM_M,
    VITE_PREMIUM_Y_ID: PREMIUM_Y,
    VITE_API_URL: API_URL,
    VITE_API_KEY: API_KEY,
    VITE_WS_URL: WS_URL,
    VITE_DESIGN_MODE: DESIGN_MODE,
    VITE_DISCORD: DISCORD,
    VITE_GITHUB: GITHUB,
    VITE_GOOGLE_ADSENSE_CLIENT_ID: GOOGLE_ID,
    VITE_GOOGLE_ADSENSE_TXT: GOOGLE_TXT
} = import.meta.env;